print("╔════════════════════════════════╗")
print("║    WELCOME TO WORD COUNTER     ║")
print("╚════════════════════════════════╝")
text=input('ENTER TEXT=')
print('='*40)
print('📊 RESULTS')
print('='*40)
words=len(text.split())
characters=len(text)
leters=sum(c.isalpha() for c in text)
numbers=sum(c.isdigit() for c in text)
spaces=text.count(' ')
sentences=text.count('.')+text.count('!')+text.count('?')
print(f'The Number of words in text={words}')
print(f'The Number of characters in text={characters}')
print(f'The Number of letters in text={leters}')
print(f'The Number of numbers in text={numbers}')
print(f'The Number of spaces in text={spaces}')
print(f'The Number of sentences in text={sentences}')
print('='*40)
print('Thanks For Using.......')
